CREATE TABLE FOREX_RATE (
  FROM_CUR CHAR(3),
  TO_CUR CHAR(3),
  DT_CONV TIMESTAMP(0),
  CONV_RATE NUMBER(38, 10)
);


CREATE TABLE SALES (
  TXN_ID NUMBER(38, 0),
  TXN_DT TIMESTAMP(9),
  PRD_ID NUMBER(38, 0),
  CUR_CD CHAR(3),
  TXN_AMT NUMBER(38, 2)
);


SELECT
  TXN_ID,
  TXN_DT,
  PRD_ID,
  CUR_CD,
  TXN_AMT,
  TXN_AMT * CONV_RATE AS TXN_AMT_USD
FROM SALES S
LEFT OUTER JOIN FOREX_RATE FX
  ON FX.FROM_CUR = S.CUR_CD
  AND FX.TO_CUR = 'USD'
  AND TRUNC(S.TXN_DT) = TRUNC(DT_CONV)
  
  
  
  SELECT
  TXN_ID,
  TXN_DT,
  PRD_ID,
  CUR_CD,
  TXN_AMT,
  CASE CUR_CD
    WHEN 'USD' THEN TXN_AMT
    ELSE TXN_AMT * CONV_RATE END
  AS TXN_AMT_USD
FROM SALES S
LEFT OUTER JOIN FOREX_RATE FX
  ON FX.FROM_CUR = S.CUR_CD
  AND FX.TO_CUR = 'USD'
  AND TRUNC(S.TXN_DT) = TRUNC(DT_CONV)